import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Badge } from '@/components/ui/badge';

interface ExtendedReactionsProps {
  postId: string;
  currentReaction?: string;
  reactionCounts?: Record<string, number>;
  onReact: (postId: string, reactionType: string) => void;
  className?: string;
}

const REACTION_CATEGORIES = [
  {
    name: 'Smileys & People',
    icon: '😊',
    reactions: [
      { type: 'grinning', emoji: '😀' },
      { type: 'grinning_eyes', emoji: '😃' },
      { type: 'grinning_big_eyes', emoji: '😄' },
      { type: 'grinning_squinting', emoji: '😆' },
      { type: 'grinning_sweat', emoji: '😅' },
      { type: 'rolling_on_floor_laughing', emoji: '🤣' },
      { type: 'face_with_tears_of_joy', emoji: '😂' },
      { type: 'slightly_smiling', emoji: '🙂' },
      { type: 'upside_down', emoji: '🙃' },
      { type: 'melting_face', emoji: '🫠' },
      { type: 'winking', emoji: '😉' },
      { type: 'smiling', emoji: '😊' },
      { type: 'smiling_halo', emoji: '😇' },
      { type: 'smiling_heart_eyes', emoji: '😍' },
      { type: 'star_struck', emoji: '🤩' },
      { type: 'face_blowing_kiss', emoji: '😘' },
      { type: 'kissing', emoji: '😗' },
      { type: 'smiling_closed_eyes', emoji: '☺️' },
      { type: 'kissing_closed_eyes', emoji: '😚' },
      { type: 'kissing_smiling_eyes', emoji: '😙' },
      { type: 'smiling_smiling_eyes', emoji: '😋' },
      { type: 'face_with_tongue', emoji: '😛' },
      { type: 'winking_tongue', emoji: '😜' },
      { type: 'zany_face', emoji: '🤪' },
      { type: 'squinting_tongue', emoji: '😝' },
      { type: 'money_mouth', emoji: '🤑' },
      { type: 'smiling_sunglasses', emoji: '😎' },
      { type: 'nerd_face', emoji: '🤓' },
      { type: 'face_with_monocle', emoji: '🧐' },
      { type: 'confused', emoji: '😕' },
      { type: 'face_with_raised_eyebrow', emoji: '🤨' },
      { type: 'neutral_face', emoji: '😐' },
      { type: 'expressionless', emoji: '😑' },
      { type: 'face_without_mouth', emoji: '😶' },
      { type: 'dotted_line_face', emoji: '🫥' },
      { type: 'face_in_clouds', emoji: '😶‍🌫️' },
      { type: 'smirking', emoji: '😏' },
      { type: 'unamused', emoji: '😒' },
      { type: 'face_with_rolling_eyes', emoji: '🙄' },
      { type: 'grimacing', emoji: '😬' },
      { type: 'face_exhaling', emoji: '😮‍💨' },
      { type: 'lying_face', emoji: '🤥' },
      { type: 'shaking_face', emoji: '😵‍💫' },
      { type: 'relieved', emoji: '😌' },
      { type: 'pensive', emoji: '😔' },
      { type: 'sleepy', emoji: '😪' },
      { type: 'drooling', emoji: '🤤' },
      { type: 'sleeping', emoji: '😴' },
      { type: 'face_with_medical_mask', emoji: '😷' },
      { type: 'face_with_thermometer', emoji: '🤒' },
      { type: 'face_with_head_bandage', emoji: '🤕' },
      { type: 'nauseated_face', emoji: '🤢' },
      { type: 'face_vomiting', emoji: '🤮' },
      { type: 'sneezing_face', emoji: '🤧' },
      { type: 'hot_face', emoji: '🥵' },
      { type: 'cold_face', emoji: '🥶' },
      { type: 'woozy_face', emoji: '🥴' },
      { type: 'face_with_crossed_out_eyes', emoji: '😵' },
      { type: 'face_with_spiral_eyes', emoji: '😵‍💫' },
      { type: 'exploding_head', emoji: '🤯' },
      { type: 'cowboy_hat_face', emoji: '🤠' },
      { type: 'partying_face', emoji: '🥳' },
      { type: 'disguised_face', emoji: '🥸' },
      { type: 'smiling_with_sunglasses', emoji: '😎' },
      { type: 'nerd_face', emoji: '🤓' },
      { type: 'face_with_monocle', emoji: '🧐' },
      { type: 'confused', emoji: '😕' },
      { type: 'worried', emoji: '😟' },
      { type: 'slightly_frowning', emoji: '🙁' },
      { type: 'frowning', emoji: '☹️' },
      { type: 'face_with_open_mouth', emoji: '😮' },
      { type: 'hushed', emoji: '😯' },
      { type: 'astonished', emoji: '😲' },
      { type: 'flushed', emoji: '😳' },
      { type: 'pleading_face', emoji: '🥺' },
      { type: 'face_holding_back_tears', emoji: '🥹' },
      { type: 'frowning_with_open_mouth', emoji: '😦' },
      { type: 'anguished', emoji: '😧' },
      { type: 'fearful', emoji: '😨' },
      { type: 'anxious_face_with_sweat', emoji: '😰' },
      { type: 'sad_but_relieved', emoji: '😥' },
      { type: 'crying', emoji: '😢' },
      { type: 'loudly_crying', emoji: '😭' },
      { type: 'face_screaming_in_fear', emoji: '😱' },
      { type: 'confounded', emoji: '😖' },
      { type: 'persevering', emoji: '😣' },
      { type: 'disappointed', emoji: '😞' },
      { type: 'downcast_with_sweat', emoji: '😓' },
      { type: 'weary', emoji: '😩' },
      { type: 'tired', emoji: '😫' },
      { type: 'yawning_face', emoji: '🥱' },
      { type: 'face_with_steam_from_nose', emoji: '😤' },
      { type: 'enraged', emoji: '😡' },
      { type: 'angry', emoji: '😠' },
      { type: 'face_with_symbols_on_mouth', emoji: '🤬' },
      { type: 'smiling_with_horns', emoji: '😈' },
      { type: 'angry_with_horns', emoji: '👿' },
      { type: 'skull', emoji: '💀' },
      { type: 'skull_and_crossbones', emoji: '☠️' },
      { type: 'pile_of_poo', emoji: '💩' },
      { type: 'clown_face', emoji: '🤡' },
      { type: 'ogre', emoji: '👹' },
      { type: 'goblin', emoji: '👺' },
      { type: 'ghost', emoji: '👻' },
      { type: 'alien', emoji: '👽' },
      { type: 'alien_monster', emoji: '👾' },
      { type: 'robot', emoji: '🤖' },
      { type: 'grinning_cat', emoji: '😺' },
      { type: 'grinning_cat_with_smiling_eyes', emoji: '😸' },
      { type: 'cat_with_tears_of_joy', emoji: '😹' },
      { type: 'smiling_cat_with_heart_eyes', emoji: '😻' },
      { type: 'cat_with_wry_smile', emoji: '😼' },
      { type: 'kissing_cat', emoji: '😽' },
      { type: 'weary_cat', emoji: '🙀' },
      { type: 'crying_cat', emoji: '😿' },
      { type: 'pouting_cat', emoji: '😾' },
      { type: 'see_no_evil', emoji: '🙈' },
      { type: 'hear_no_evil', emoji: '🙉' },
      { type: 'speak_no_evil', emoji: '🙊' },
      { type: 'kiss_mark', emoji: '💋' },
      { type: 'love_letter', emoji: '💌' },
      { type: 'heart_with_arrow', emoji: '💘' },
      { type: 'heart_with_ribbon', emoji: '💝' },
      { type: 'sparkling_heart', emoji: '💖' },
      { type: 'growing_heart', emoji: '💗' },
      { type: 'beating_heart', emoji: '💓' },
      { type: 'revolving_hearts', emoji: '💞' },
      { type: 'two_hearts', emoji: '💕' },
      { type: 'heart_decoration', emoji: '💟' },
      { type: 'heart_exclamation', emoji: '❣️' },
      { type: 'broken_heart', emoji: '💔' },
      { type: 'heart_on_fire', emoji: '❤️‍🔥' },
      { type: 'mending_heart', emoji: '❤️‍🩹' },
      { type: 'red_heart', emoji: '❤️' },
      { type: 'orange_heart', emoji: '🧡' },
      { type: 'yellow_heart', emoji: '💛' },
      { type: 'green_heart', emoji: '💚' },
      { type: 'blue_heart', emoji: '💙' },
      { type: 'purple_heart', emoji: '💜' },
      { type: 'brown_heart', emoji: '🤎' },
      { type: 'black_heart', emoji: '🖤' },
      { type: 'grey_heart', emoji: '🩶' },
      { type: 'white_heart', emoji: '🤍' },
      { type: 'pink_heart', emoji: '🩷' },
      { type: 'light_blue_heart', emoji: '🩵' },
      { type: 'waving_hand', emoji: '👋' },
      { type: 'raised_back_of_hand', emoji: '🤚' },
      { type: 'hand_with_fingers_splayed', emoji: '🖐️' },
      { type: 'raised_hand', emoji: '✋' },
      { type: 'vulcan_salute', emoji: '🖖' },
      { type: 'rightwards_hand', emoji: '🫱' },
      { type: 'leftwards_hand', emoji: '🫲' },
      { type: 'palm_down_hand', emoji: '🫳' },
      { type: 'palm_up_hand', emoji: '🫴' },
      { type: 'leftwards_pushing_hand', emoji: '🫷' },
      { type: 'rightwards_pushing_hand', emoji: '🫸' },
      { type: 'ok_hand', emoji: '👌' },
      { type: 'pinched_fingers', emoji: '🤌' },
      { type: 'pinching_hand', emoji: '🤏' },
      { type: 'victory_hand', emoji: '✌️' },
      { type: 'crossed_fingers', emoji: '🤞' },
      { type: 'hand_with_index_finger_and_thumb_crossed', emoji: '🫰' },
      { type: 'love_you_gesture', emoji: '🤟' },
      { type: 'sign_of_the_horns', emoji: '🤘' },
      { type: 'call_me_hand', emoji: '🤙' },
      { type: 'backhand_index_pointing_left', emoji: '👈' },
      { type: 'backhand_index_pointing_right', emoji: '👉' },
      { type: 'backhand_index_pointing_up', emoji: '👆' },
      { type: 'middle_finger', emoji: '🖕' },
      { type: 'backhand_index_pointing_down', emoji: '👇' },
      { type: 'index_pointing_up', emoji: '☝️' },
      { type: 'index_pointing_at_the_viewer', emoji: '🫵' },
      { type: 'thumbs_up', emoji: '👍' },
      { type: 'thumbs_down', emoji: '👎' },
      { type: 'raised_fist', emoji: '✊' },
      { type: 'oncoming_fist', emoji: '👊' },
      { type: 'left_facing_fist', emoji: '🤛' },
      { type: 'right_facing_fist', emoji: '🤜' },
      { type: 'clapping_hands', emoji: '👏' },
      { type: 'raising_hands', emoji: '🙌' },
      { type: 'heart_hands', emoji: '🫶' },
      { type: 'open_hands', emoji: '👐' },
      { type: 'palms_up_together', emoji: '🤲' },
      { type: 'handshake', emoji: '🤝' },
      { type: 'folded_hands', emoji: '🙏' },
      { type: 'writing_hand', emoji: '✍️' },
      { type: 'nail_polish', emoji: '💅' },
      { type: 'selfie', emoji: '🤳' },
      { type: 'flexed_biceps', emoji: '💪' },
      { type: 'mechanical_arm', emoji: '🦾' },
      { type: 'mechanical_leg', emoji: '🦿' },
      { type: 'leg', emoji: '🦵' },
      { type: 'foot', emoji: '🦶' },
      { type: 'ear', emoji: '👂' },
      { type: 'ear_with_hearing_aid', emoji: '🦻' },
      { type: 'nose', emoji: '👃' },
      { type: 'brain', emoji: '🧠' },
      { type: 'anatomical_heart', emoji: '🫀' },
      { type: 'lungs', emoji: '🫁' },
      { type: 'tooth', emoji: '🦷' },
      { type: 'bone', emoji: '🦴' },
      { type: 'eyes', emoji: '👀' },
      { type: 'eye', emoji: '👁️' },
      { type: 'tongue', emoji: '👅' },
      { type: 'mouth', emoji: '👄' },
      { type: 'biting_lip', emoji: '🫦' },
      { type: 'baby', emoji: '👶' },
      { type: 'child', emoji: '🧒' },
      { type: 'boy', emoji: '👦' },
      { type: 'girl', emoji: '👧' },
      { type: 'person', emoji: '🧑' },
      { type: 'person_blond_hair', emoji: '👱' },
      { type: 'man', emoji: '👨' },
      { type: 'person_beard', emoji: '🧔' },
      { type: 'person_red_hair', emoji: '👨‍🦰' },
      { type: 'person_curly_hair', emoji: '👨‍🦱' },
      { type: 'person_white_hair', emoji: '👨‍🦳' },
      { type: 'person_bald', emoji: '👨‍🦲' },
      { type: 'woman', emoji: '👩' },
      { type: 'person_red_hair_woman', emoji: '👩‍🦰' },
      { type: 'person_curly_hair_woman', emoji: '👩‍🦱' },
      { type: 'person_white_hair_woman', emoji: '👩‍🦳' },
      { type: 'person_bald_woman', emoji: '👩‍🦲' },
      { type: 'blond_haired_woman', emoji: '👱‍♀️' },
      { type: 'blond_haired_man', emoji: '👱‍♂️' },
      { type: 'older_person', emoji: '🧓' },
      { type: 'old_man', emoji: '👴' },
      { type: 'old_woman', emoji: '👵' },
    ]
  },
  {
    name: 'Hearts & Symbols',
    icon: '❤️',
    reactions: [
      { type: 'red_heart', emoji: '❤️' },
      { type: 'orange_heart', emoji: '🧡' },
      { type: 'yellow_heart', emoji: '💛' },
      { type: 'green_heart', emoji: '💚' },
      { type: 'blue_heart', emoji: '💙' },
      { type: 'purple_heart', emoji: '💜' },
      { type: 'brown_heart', emoji: '🤎' },
      { type: 'black_heart', emoji: '🖤' },
      { type: 'grey_heart', emoji: '🩶' },
      { type: 'white_heart', emoji: '🤍' },
      { type: 'pink_heart', emoji: '🩷' },
      { type: 'light_blue_heart', emoji: '🩵' },
      { type: 'heart_with_arrow', emoji: '💘' },
      { type: 'heart_with_ribbon', emoji: '💝' },
      { type: 'sparkling_heart', emoji: '💖' },
      { type: 'growing_heart', emoji: '💗' },
      { type: 'beating_heart', emoji: '💓' },
      { type: 'revolving_hearts', emoji: '💞' },
      { type: 'two_hearts', emoji: '💕' },
      { type: 'heart_decoration', emoji: '💟' },
      { type: 'heart_exclamation', emoji: '❣️' },
      { type: 'broken_heart', emoji: '💔' },
      { type: 'heart_on_fire', emoji: '❤️‍🔥' },
      { type: 'mending_heart', emoji: '❤️‍🩹' },
      { type: 'sparkles', emoji: '✨' },
      { type: 'star', emoji: '⭐' },
      { type: 'glowing_star', emoji: '🌟' },
      { type: 'dizzy_star', emoji: '💫' },
      { type: 'shooting_star', emoji: '🌠' },
      { type: 'comet', emoji: '☄️' },
      { type: 'lightning', emoji: '⚡' },
      { type: 'fire', emoji: '🔥' },
      { type: 'boom', emoji: '💥' },
      { type: 'collision', emoji: '💥' },
      { type: 'hundred', emoji: '💯' },
      { type: 'gem', emoji: '💎' },
      { type: 'crown', emoji: '👑' },
      { type: 'trophy', emoji: '🏆' },
      { type: 'medal_sports', emoji: '🏅' },
      { type: '1st_place_medal', emoji: '🥇' },
      { type: '2nd_place_medal', emoji: '🥈' },
      { type: '3rd_place_medal', emoji: '🥉' },
      { type: 'ribbon', emoji: '🎀' },
      { type: 'gift', emoji: '🎁' },
      { type: 'reminder_ribbon', emoji: '🎗️' },
      { type: 'rosette', emoji: '🏵️' },
      { type: 'ticket', emoji: '🎫' },
      { type: 'admission_tickets', emoji: '🎟️' },
      { type: 'warning', emoji: '⚠️' },
      { type: 'children_crossing', emoji: '🚸' },
      { type: 'no_entry', emoji: '⛔' },
      { type: 'no_entry_sign', emoji: '🚫' },
      { type: 'no_bicycles', emoji: '🚳' },
      { type: 'no_smoking', emoji: '🚭' },
      { type: 'no_littering', emoji: '🚯' },
      { type: 'non_potable_water', emoji: '🚱' },
      { type: 'no_pedestrians', emoji: '🚷' },
      { type: 'no_mobile_phones', emoji: '📵' },
      { type: 'underage', emoji: '🔞' },
      { type: 'radioactive', emoji: '☢️' },
      { type: 'biohazard', emoji: '☣️' },
      { type: 'up_arrow', emoji: '⬆️' },
      { type: 'up_right_arrow', emoji: '↗️' },
      { type: 'right_arrow', emoji: '➡️' },
      { type: 'down_right_arrow', emoji: '↘️' },
      { type: 'down_arrow', emoji: '⬇️' },
      { type: 'down_left_arrow', emoji: '↙️' },
      { type: 'left_arrow', emoji: '⬅️' },
      { type: 'up_left_arrow', emoji: '↖️' },
      { type: 'up_down_arrow', emoji: '↕️' },
      { type: 'left_right_arrow', emoji: '↔️' },
      { type: 'leftwards_arrow_with_hook', emoji: '↩️' },
      { type: 'rightwards_arrow_with_hook', emoji: '↪️' },
      { type: 'arrow_heading_up', emoji: '⤴️' },
      { type: 'arrow_heading_down', emoji: '⤵️' },
      { type: 'arrows_clockwise', emoji: '🔃' },
      { type: 'arrows_counterclockwise', emoji: '🔄' },
      { type: 'back_arrow', emoji: '🔙' },
      { type: 'end_arrow', emoji: '🔚' },
      { type: 'on_arrow', emoji: '🔛' },
      { type: 'soon_arrow', emoji: '🔜' },
      { type: 'top_arrow', emoji: '🔝' },
    ]
  },
  {
    name: 'Activities & Objects',
    icon: '🎉',
    reactions: [
      { type: 'celebrate', emoji: '🎉' },
      { type: 'party_popper', emoji: '🎊' },
      { type: 'confetti_ball', emoji: '🎊' },
      { type: 'rocket', emoji: '🚀' },
      { type: 'airplane', emoji: '✈️' },
      { type: 'helicopter', emoji: '🚁' },
      { type: 'parachute', emoji: '🪂' },
      { type: 'seat', emoji: '💺' },
      { type: 'anchor', emoji: '⚓' },
      { type: 'sailboat', emoji: '⛵' },
      { type: 'speedboat', emoji: '🚤' },
      { type: 'passenger_ship', emoji: '🛳️' },
      { type: 'ferry', emoji: '⛴️' },
      { type: 'motor_boat', emoji: '🛥️' },
      { type: 'ship', emoji: '🚢' },
      { type: 'car', emoji: '🚗' },
      { type: 'taxi', emoji: '🚕' },
      { type: 'bus', emoji: '🚌' },
      { type: 'trolleybus', emoji: '🚎' },
      { type: 'racing_car', emoji: '🏎️' },
      { type: 'police_car', emoji: '🚓' },
      { type: 'ambulance', emoji: '🚑' },
      { type: 'fire_engine', emoji: '🚒' },
      { type: 'minibus', emoji: '🚐' },
      { type: 'truck', emoji: '🚚' },
      { type: 'articulated_lorry', emoji: '🚛' },
      { type: 'tractor', emoji: '🚜' },
      { type: 'racing_motorcycle', emoji: '🏍️' },
      { type: 'motor_scooter', emoji: '🛵' },
      { type: 'manual_wheelchair', emoji: '🦽' },
      { type: 'motorized_wheelchair', emoji: '🦼' },
      { type: 'auto_rickshaw', emoji: '🛺' },
      { type: 'bicycle', emoji: '🚲' },
      { type: 'kick_scooter', emoji: '🛴' },
      { type: 'skateboard', emoji: '🛹' },
      { type: 'roller_skate', emoji: '🛼' },
      { type: 'mountain_railway', emoji: '🚞' },
      { type: 'railway_car', emoji: '🚃' },
      { type: 'high_speed_train', emoji: '🚄' },
      { type: 'bullet_train', emoji: '🚅' },
      { type: 'train', emoji: '🚆' },
      { type: 'metro', emoji: '🚇' },
      { type: 'light_rail', emoji: '🚈' },
      { type: 'station', emoji: '🚉' },
      { type: 'tram', emoji: '🚊' },
      { type: 'monorail', emoji: '🚝' },
      { type: 'mountain_cableway', emoji: '🚠' },
      { type: 'aerial_tramway', emoji: '🚡' },
      { type: 'suspension_railway', emoji: '🚟' },
      { type: 'railway_track', emoji: '🛤️' },
      { type: 'motorway', emoji: '🛣️' },
      { type: 'construction', emoji: '🚧' },
      { type: 'fuel_pump', emoji: '⛽' },
      { type: 'rotating_light', emoji: '🚨' },
      { type: 'traffic_light', emoji: '🚥' },
      { type: 'vertical_traffic_light', emoji: '🚦' },
      { type: 'stop_sign', emoji: '🛑' },
      { type: 'checkered_flag', emoji: '🏁' },
      { type: 'watch', emoji: '⌚' },
      { type: 'mobile_phone', emoji: '📱' },
      { type: 'calling', emoji: '📲' },
      { type: 'computer', emoji: '💻' },
      { type: 'keyboard', emoji: '⌨️' },
      { type: 'desktop_computer', emoji: '🖥️' },
      { type: 'printer', emoji: '🖨️' },
      { type: 'mouse', emoji: '🖱️' },
      { type: 'trackball', emoji: '🖲️' },
      { type: 'joystick', emoji: '🕹️' },
      { type: 'compression', emoji: '🗜️' },
      { type: 'minidisc', emoji: '💽' },
      { type: 'floppy_disk', emoji: '💾' },
      { type: 'cd', emoji: '💿' },
      { type: 'dvd', emoji: '📀' },
      { type: 'abacus', emoji: '🧮' },
      { type: 'movie_camera', emoji: '🎥' },
      { type: 'film_strip', emoji: '🎞️' },
      { type: 'camera', emoji: '📷' },
      { type: 'camera_with_flash', emoji: '📸' },
      { type: 'video_camera', emoji: '📹' },
      { type: 'vhs', emoji: '📼' },
      { type: 'mag', emoji: '🔍' },
      { type: 'mag_right', emoji: '🔎' },
      { type: 'candle', emoji: '🕯️' },
      { type: 'bulb', emoji: '💡' },
      { type: 'flashlight', emoji: '🔦' },
      { type: 'red_paper_lantern', emoji: '🏮' },
      { type: 'diya_lamp', emoji: '🪔' },
      { type: 'notebook_with_decorative_cover', emoji: '📔' },
      { type: 'closed_book', emoji: '📕' },
      { type: 'open_book', emoji: '📖' },
      { type: 'green_book', emoji: '📗' },
      { type: 'blue_book', emoji: '📘' },
      { type: 'orange_book', emoji: '📙' },
      { type: 'books', emoji: '📚' },
      { type: 'notebook', emoji: '📓' },
      { type: 'ledger', emoji: '📒' },
      { type: 'page_with_curl', emoji: '📃' },
      { type: 'scroll', emoji: '📜' },
      { type: 'page_facing_up', emoji: '📄' },
      { type: 'newspaper', emoji: '📰' },
      { type: 'rolled_up_newspaper', emoji: '🗞️' },
      { type: 'bookmark_tabs', emoji: '📑' },
      { type: 'bookmark', emoji: '🔖' },
      { type: 'label', emoji: '🏷️' },
    ]
  },
  {
    name: 'Nature',
    icon: '🌸',
    reactions: [
      { type: 'monkey_face', emoji: '🐵' },
      { type: 'monkey', emoji: '🐒' },
      { type: 'gorilla', emoji: '🦍' },
      { type: 'orangutan', emoji: '🦧' },
      { type: 'dog_face', emoji: '🐶' },
      { type: 'dog', emoji: '🐕' },
      { type: 'guide_dog', emoji: '🦮' },
      { type: 'service_dog', emoji: '🐕‍🦺' },
      { type: 'poodle', emoji: '🐩' },
      { type: 'wolf', emoji: '🐺' },
      { type: 'fox_face', emoji: '🦊' },
      { type: 'raccoon', emoji: '🦝' },
      { type: 'cat_face', emoji: '🐱' },
      { type: 'cat', emoji: '🐈' },
      { type: 'black_cat', emoji: '🐈‍⬛' },
      { type: 'lion', emoji: '🦁' },
      { type: 'tiger_face', emoji: '🐯' },
      { type: 'tiger', emoji: '🐅' },
      { type: 'leopard', emoji: '🐆' },
      { type: 'horse_face', emoji: '🐴' },
      { type: 'horse', emoji: '🐎' },
      { type: 'unicorn', emoji: '🦄' },
      { type: 'zebra', emoji: '🦓' },
      { type: 'deer', emoji: '🦌' },
      { type: 'bison', emoji: '🦬' },
      { type: 'cow_face', emoji: '🐮' },
      { type: 'ox', emoji: '🐂' },
      { type: 'water_buffalo', emoji: '🐃' },
      { type: 'cow', emoji: '🐄' },
      { type: 'pig_face', emoji: '🐷' },
      { type: 'pig', emoji: '🐖' },
      { type: 'boar', emoji: '🐗' },
      { type: 'pig_nose', emoji: '🐽' },
      { type: 'ram', emoji: '🐏' },
      { type: 'ewe', emoji: '🐑' },
      { type: 'goat', emoji: '🐐' },
      { type: 'dromedary_camel', emoji: '🐪' },
      { type: 'camel', emoji: '🐫' },
      { type: 'llama', emoji: '🦙' },
      { type: 'giraffe', emoji: '🦒' },
      { type: 'elephant', emoji: '🐘' },
      { type: 'mammoth', emoji: '🦣' },
      { type: 'rhinoceros', emoji: '🦏' },
      { type: 'hippopotamus', emoji: '🦛' },
      { type: 'mouse_face', emoji: '🐭' },
      { type: 'mouse', emoji: '🐁' },
      { type: 'rat', emoji: '🐀' },
      { type: 'hamster', emoji: '🐹' },
      { type: 'rabbit_face', emoji: '🐰' },
      { type: 'rabbit', emoji: '🐇' },
      { type: 'chipmunk', emoji: '🐿️' },
      { type: 'beaver', emoji: '🦫' },
      { type: 'hedgehog', emoji: '🦔' },
      { type: 'bat', emoji: '🦇' },
      { type: 'bear', emoji: '🐻' },
      { type: 'polar_bear', emoji: '🐻‍❄️' },
      { type: 'koala', emoji: '🐨' },
      { type: 'panda_face', emoji: '🐼' },
      { type: 'sloth', emoji: '🦥' },
      { type: 'otter', emoji: '🦦' },
      { type: 'skunk', emoji: '🦨' },
      { type: 'kangaroo', emoji: '🦘' },
      { type: 'badger', emoji: '🦡' },
      { type: 'feet', emoji: '🐾' },
      { type: 'turkey', emoji: '🦃' },
      { type: 'chicken', emoji: '🐔' },
      { type: 'rooster', emoji: '🐓' },
      { type: 'hatching_chick', emoji: '🐣' },
      { type: 'baby_chick', emoji: '🐤' },
      { type: 'front_facing_baby_chick', emoji: '🐥' },
      { type: 'bird', emoji: '🐦' },
      { type: 'penguin', emoji: '🐧' },
      { type: 'dove', emoji: '🕊️' },
      { type: 'eagle', emoji: '🦅' },
      { type: 'duck', emoji: '🦆' },
      { type: 'swan', emoji: '🦢' },
      { type: 'owl', emoji: '🦉' },
      { type: 'dodo', emoji: '🦤' },
      { type: 'feather', emoji: '🪶' },
      { type: 'flamingo', emoji: '🦩' },
      { type: 'peacock', emoji: '🦚' },
      { type: 'parrot', emoji: '🦜' },
      { type: 'wing', emoji: '🪽' },
      { type: 'black_bird', emoji: '🐦‍⬛' },
      { type: 'goose', emoji: '🪿' },
      { type: 'frog', emoji: '🐸' },
      { type: 'crocodile', emoji: '🐊' },
      { type: 'turtle', emoji: '🐢' },
      { type: 'lizard', emoji: '🦎' },
      { type: 'snake', emoji: '🐍' },
      { type: 'dragon_face', emoji: '🐲' },
      { type: 'dragon', emoji: '🐉' },
      { type: 'sauropod', emoji: '🦕' },
      { type: 't_rex', emoji: '🦖' },
      { type: 'whale', emoji: '🐳' },
      { type: 'whale2', emoji: '🐋' },
      { type: 'dolphin', emoji: '🐬' },
      { type: 'seal', emoji: '🦭' },
      { type: 'fish', emoji: '🐟' },
      { type: 'tropical_fish', emoji: '🐠' },
      { type: 'blowfish', emoji: '🐡' },
      { type: 'shark', emoji: '🦈' },
      { type: 'octopus', emoji: '🐙' },
      { type: 'shell', emoji: '🐚' },
      { type: 'coral', emoji: '🪸' },
      { type: 'snail', emoji: '🐌' },
      { type: 'butterfly', emoji: '🦋' },
      { type: 'bug', emoji: '🐛' },
      { type: 'ant', emoji: '🐜' },
      { type: 'bee', emoji: '🐝' },
      { type: 'beetle', emoji: '🪲' },
      { type: 'lady_beetle', emoji: '🐞' },
      { type: 'cricket', emoji: '🦗' },
      { type: 'cockroach', emoji: '🪳' },
      { type: 'spider', emoji: '🕷️' },
      { type: 'spider_web', emoji: '🕸️' },
      { type: 'scorpion', emoji: '🦂' },
      { type: 'mosquito', emoji: '🦟' },
      { type: 'fly', emoji: '🪰' },
      { type: 'worm', emoji: '🪱' },
      { type: 'microbe', emoji: '🦠' },
      { type: 'bouquet', emoji: '💐' },
      { type: 'cherry_blossom', emoji: '🌸' },
      { type: 'white_flower', emoji: '💮' },
      { type: 'lotus', emoji: '🪷' },
      { type: 'rosette', emoji: '🏵️' },
      { type: 'rose', emoji: '🌹' },
      { type: 'wilted_flower', emoji: '🥀' },
      { type: 'hibiscus', emoji: '🌺' },
      { type: 'sunflower', emoji: '🌻' },
      { type: 'blossom', emoji: '🌼' },
      { type: 'tulip', emoji: '🌷' },
      { type: 'hyacinth', emoji: '🪻' },
      { type: 'seedling', emoji: '🌱' },
      { type: 'potted_plant', emoji: '🪴' },
      { type: 'evergreen_tree', emoji: '🌲' },
      { type: 'deciduous_tree', emoji: '🌳' },
      { type: 'palm_tree', emoji: '🌴' },
      { type: 'cactus', emoji: '🌵' },
      { type: 'ear_of_rice', emoji: '🌾' },
      { type: 'herb', emoji: '🌿' },
      { type: 'shamrock', emoji: '☘️' },
      { type: 'four_leaf_clover', emoji: '🍀' },
      { type: 'maple_leaf', emoji: '🍁' },
      { type: 'fallen_leaves', emoji: '🍂' },
      { type: 'leaves', emoji: '🍃' },
      { type: 'empty_nest', emoji: '🪹' },
      { type: 'nest_with_eggs', emoji: '🪺' },
      { type: 'mushroom', emoji: '🍄' },
      { type: 'grapes', emoji: '🍇' },
      { type: 'melon', emoji: '🍈' },
      { type: 'watermelon', emoji: '🍉' },
      { type: 'tangerine', emoji: '🍊' },
      { type: 'lemon', emoji: '🍋' },
      { type: 'lime', emoji: '🍋‍🟩' },
      { type: 'banana', emoji: '🍌' },
      { type: 'pineapple', emoji: '🍍' },
      { type: 'mango', emoji: '🥭' },
      { type: 'apple', emoji: '🍎' },
      { type: 'green_apple', emoji: '🍏' },
      { type: 'pear', emoji: '🍐' },
      { type: 'peach', emoji: '🍑' },
      { type: 'cherries', emoji: '🍒' },
      { type: 'strawberry', emoji: '🍓' },
      { type: 'blueberries', emoji: '🫐' },
      { type: 'kiwi_fruit', emoji: '🥝' },
      { type: 'tomato', emoji: '🍅' },
      { type: 'olive', emoji: '🫒' },
      { type: 'coconut', emoji: '🥥' },
      { type: 'avocado', emoji: '🥑' },
      { type: 'eggplant', emoji: '🍆' },
      { type: 'potato', emoji: '🥔' },
      { type: 'carrot', emoji: '🥕' },
      { type: 'corn', emoji: '🌽' },
      { type: 'hot_pepper', emoji: '🌶️' },
      { type: 'bell_pepper', emoji: '🫑' },
      { type: 'cucumber', emoji: '🥒' },
      { type: 'leafy_greens', emoji: '🥬' },
      { type: 'broccoli', emoji: '🥦' },
      { type: 'garlic', emoji: '🧄' },
      { type: 'onion', emoji: '🧅' },
      { type: 'peanuts', emoji: '🥜' },
      { type: 'beans', emoji: '🫘' },
      { type: 'chestnut', emoji: '🌰' },
      { type: 'ginger', emoji: '🫚' },
      { type: 'pea_pod', emoji: '🫛' },
      { type: 'brown_mushroom', emoji: '🍄‍🟫' },
      { type: 'bread', emoji: '🍞' },
      { type: 'croissant', emoji: '🥐' },
      { type: 'baguette_bread', emoji: '🥖' },
      { type: 'flatbread', emoji: '🫓' },
      { type: 'pretzel', emoji: '🥨' },
      { type: 'bagel', emoji: '🥯' },
      { type: 'pancakes', emoji: '🥞' },
      { type: 'waffle', emoji: '🧇' },
      { type: 'cheese', emoji: '🧀' },
      { type: 'meat_on_bone', emoji: '🍖' },
      { type: 'poultry_leg', emoji: '🍗' },
      { type: 'cut_of_meat', emoji: '🥩' },
      { type: 'bacon', emoji: '🥓' },
      { type: 'hamburger', emoji: '🍔' },
      { type: 'fries', emoji: '🍟' },
      { type: 'pizza', emoji: '🍕' },
      { type: 'hotdog', emoji: '🌭' },
      { type: 'sandwich', emoji: '🥪' },
      { type: 'taco', emoji: '🌮' },
      { type: 'burrito', emoji: '🌯' },
      { type: 'tamale', emoji: '🫔' },
      { type: 'stuffed_flatbread', emoji: '🥙' },
      { type: 'falafel', emoji: '🧆' },
      { type: 'egg', emoji: '🥚' },
      { type: 'fried_egg', emoji: '🍳' },
      { type: 'shallow_pan_of_food', emoji: '🥘' },
      { type: 'stew', emoji: '🍲' },
      { type: 'fondue', emoji: '🫕' },
      { type: 'bowl_with_spoon', emoji: '🥣' },
      { type: 'green_salad', emoji: '🥗' },
      { type: 'popcorn', emoji: '🍿' },
      { type: 'butter', emoji: '🧈' },
      { type: 'salt', emoji: '🧂' },
      { type: 'canned_food', emoji: '🥫' },
      { type: 'bento', emoji: '🍱' },
      { type: 'rice_cracker', emoji: '🍘' },
      { type: 'rice_ball', emoji: '🍙' },
      { type: 'rice', emoji: '🍚' },
      { type: 'curry', emoji: '🍛' },
      { type: 'ramen', emoji: '🍜' },
      { type: 'spaghetti', emoji: '🍝' },
      { type: 'sweet_potato', emoji: '🍠' },
      { type: 'oden', emoji: '🍢' },
      { type: 'sushi', emoji: '🍣' },
      { type: 'fried_shrimp', emoji: '🍤' },
      { type: 'fish_cake', emoji: '🍥' },
      { type: 'moon_cake', emoji: '🥮' },
      { type: 'dango', emoji: '🍡' },
      { type: 'dumpling', emoji: '🥟' },
      { type: 'fortune_cookie', emoji: '🥠' },
      { type: 'takeout_box', emoji: '🥡' },
      { type: 'crab', emoji: '🦀' },
      { type: 'lobster', emoji: '🦞' },
      { type: 'shrimp', emoji: '🦐' },
      { type: 'squid', emoji: '🦑' },
      { type: 'oyster', emoji: '🦪' },
      { type: 'icecream', emoji: '🍦' },
      { type: 'shaved_ice', emoji: '🍧' },
      { type: 'ice_cream', emoji: '🍨' },
      { type: 'doughnut', emoji: '🍩' },
      { type: 'cookie', emoji: '🍪' },
      { type: 'birthday', emoji: '🎂' },
      { type: 'cake', emoji: '🍰' },
      { type: 'cupcake', emoji: '🧁' },
      { type: 'pie', emoji: '🥧' },
      { type: 'chocolate_bar', emoji: '🍫' },
      { type: 'candy', emoji: '🍬' },
      { type: 'lollipop', emoji: '🍭' },
      { type: 'custard', emoji: '🍮' },
      { type: 'honey_pot', emoji: '🍯' },
      { type: 'baby_bottle', emoji: '🍼' },
      { type: 'milk_glass', emoji: '🥛' },
      { type: 'coffee', emoji: '☕' },
      { type: 'teapot', emoji: '🫖' },
      { type: 'tea', emoji: '🍵' },
      { type: 'sake', emoji: '🍶' },
      { type: 'champagne', emoji: '🍾' },
      { type: 'wine_glass', emoji: '🍷' },
      { type: 'cocktail', emoji: '🍸' },
      { type: 'tropical_drink', emoji: '🍹' },
      { type: 'beer', emoji: '🍺' },
      { type: 'beers', emoji: '🍻' },
      { type: 'clinking_glasses', emoji: '🥂' },
      { type: 'tumbler_glass', emoji: '🥃' },
      { type: 'pouring_liquid', emoji: '🫗' },
      { type: 'cup_with_straw', emoji: '🥤' },
      { type: 'bubble_tea', emoji: '🧋' },
      { type: 'beverage_box', emoji: '🧃' },
      { type: 'mate', emoji: '🧉' },
      { type: 'ice', emoji: '🧊' },
      { type: 'chopsticks', emoji: '🥢' },
      { type: 'plate_with_cutlery', emoji: '🍽️' },
      { type: 'fork_and_knife', emoji: '🍴' },
      { type: 'spoon', emoji: '🥄' },
      { type: 'hocho', emoji: '🔪' },
      { type: 'jar', emoji: '🫙' },
      { type: 'amphora', emoji: '🏺' },
      { type: 'earth_africa', emoji: '🌍' },
      { type: 'earth_americas', emoji: '🌎' },
      { type: 'earth_asia', emoji: '🌏' },
      { type: 'globe_with_meridians', emoji: '🌐' },
      { type: 'world_map', emoji: '🗺️' },
      { type: 'japan', emoji: '🗾' },
      { type: 'compass', emoji: '🧭' },
      { type: 'snow_capped_mountain', emoji: '🏔️' },
      { type: 'mountain', emoji: '⛰️' },
      { type: 'volcano', emoji: '🌋' },
      { type: 'mount_fuji', emoji: '🗻' },
      { type: 'camping', emoji: '🏕️' },
      { type: 'beach_with_umbrella', emoji: '🏖️' },
      { type: 'desert', emoji: '🏜️' },
      { type: 'desert_island', emoji: '🏝️' },
      { type: 'national_park', emoji: '🏞️' },
      { type: 'stadium', emoji: '🏟️' },
      { type: 'classical_building', emoji: '🏛️' },
      { type: 'building_construction', emoji: '🏗️' },
      { type: 'bricks', emoji: '🧱' },
      { type: 'rock', emoji: '🪨' },
      { type: 'wood', emoji: '🪵' },
      { type: 'hut', emoji: '🛖' },
      { type: 'houses', emoji: '🏘️' },
      { type: 'derelict_house', emoji: '🏚️' },
      { type: 'house', emoji: '🏠' },
      { type: 'house_with_garden', emoji: '🏡' },
      { type: 'office', emoji: '🏢' },
      { type: 'post_office', emoji: '🏣' },
      { type: 'european_post_office', emoji: '🏤' },
      { type: 'hospital', emoji: '🏥' },
      { type: 'bank', emoji: '🏦' },
      { type: 'hotel', emoji: '🏨' },
      { type: 'love_hotel', emoji: '🏩' },
      { type: 'convenience_store', emoji: '🏪' },
      { type: 'school', emoji: '🏫' },
      { type: 'department_store', emoji: '🏬' },
      { type: 'factory', emoji: '🏭' },
      { type: 'japanese_castle', emoji: '🏯' },
      { type: 'european_castle', emoji: '🏰' },
      { type: 'wedding', emoji: '💒' },
      { type: 'tokyo_tower', emoji: '🗼' },
      { type: 'statue_of_liberty', emoji: '🗽' },
      { type: 'church', emoji: '⛪' },
      { type: 'mosque', emoji: '🕌' },
      { type: 'hindu_temple', emoji: '🛕' },
      { type: 'synagogue', emoji: '🕍' },
      { type: 'shinto_shrine', emoji: '⛩️' },
      { type: 'kaaba', emoji: '🕋' },
      { type: 'fountain', emoji: '⛲' },
      { type: 'tent', emoji: '⛺' },
      { type: 'foggy', emoji: '🌁' },
      { type: 'night_with_stars', emoji: '🌃' },
      { type: 'cityscape', emoji: '🏙️' },
      { type: 'sunrise_over_mountains', emoji: '🌄' },
      { type: 'sunrise', emoji: '🌅' },
      { type: 'city_sunset', emoji: '🌆' },
      { type: 'city_sunrise', emoji: '🌇' },
      { type: 'bridge_at_night', emoji: '🌉' },
      { type: 'hotsprings', emoji: '♨️' },
      { type: 'carousel_horse', emoji: '🎠' },
      { type: 'playground_slide', emoji: '🛝' },
      { type: 'ferris_wheel', emoji: '🎡' },
      { type: 'roller_coaster', emoji: '🎢' },
      { type: 'barber', emoji: '💈' },
      { type: 'circus_tent', emoji: '🎪' },
      { type: 'steam_locomotive', emoji: '🚂' },
      { type: 'railway_car', emoji: '🚃' },
      { type: 'high_speed_train', emoji: '🚄' },
      { type: 'bullet_train', emoji: '🚅' },
      { type: 'train', emoji: '🚆' },
      { type: 'metro', emoji: '🚇' },
      { type: 'light_rail', emoji: '🚈' },
      { type: 'station', emoji: '🚉' },
      { type: 'tram', emoji: '🚊' },
      { type: 'monorail', emoji: '🚝' },
      { type: 'mountain_railway', emoji: '🚞' },
      { type: 'tram_car', emoji: '🚋' },
      { type: 'bus', emoji: '🚌' },
      { type: 'oncoming_bus', emoji: '🚍' },
      { type: 'trolleybus', emoji: '🚎' },
      { type: 'minibus', emoji: '🚐' },
      { type: 'ambulance', emoji: '🚑' },
      { type: 'fire_engine', emoji: '🚒' },
      { type: 'police_car', emoji: '🚓' },
      { type: 'oncoming_police_car', emoji: '🚔' },
      { type: 'taxi', emoji: '🚕' },
      { type: 'oncoming_taxi', emoji: '🚖' },
      { type: 'car', emoji: '🚗' },
      { type: 'oncoming_automobile', emoji: '🚘' },
      { type: 'blue_car', emoji: '🚙' },
      { type: 'pickup_truck', emoji: '🛻' },
      { type: 'truck', emoji: '🚚' },
      { type: 'articulated_lorry', emoji: '🚛' },
      { type: 'tractor', emoji: '🚜' },
      { type: 'racing_car', emoji: '🏎️' },
      { type: 'motorcycle', emoji: '🏍️' },
      { type: 'motor_scooter', emoji: '🛵' },
      { type: 'manual_wheelchair', emoji: '🦽' },
      { type: 'motorized_wheelchair', emoji: '🦼' },
      { type: 'auto_rickshaw', emoji: '🛺' },
      { type: 'bike', emoji: '🚲' },
      { type: 'scooter', emoji: '🛴' },
      { type: 'skateboard', emoji: '🛹' },
      { type: 'roller_skate', emoji: '🛼' },
      { type: 'busstop', emoji: '🚏' },
      { type: 'motorway', emoji: '🛣️' },
      { type: 'railway_track', emoji: '🛤️' },
      { type: 'oil_drum', emoji: '🛢️' },
      { type: 'fuelpump', emoji: '⛽' },
      { type: 'rotating_light', emoji: '🚨' },
      { type: 'traffic_light', emoji: '🚥' },
      { type: 'vertical_traffic_light', emoji: '🚦' },
      { type: 'stop_sign', emoji: '🛑' },
      { type: 'construction', emoji: '🚧' },
      { type: 'anchor', emoji: '⚓' },
      { type: 'ring_buoy', emoji: '🛟' },
      { type: 'boat', emoji: '⛵' },
      { type: 'canoe', emoji: '🛶' },
      { type: 'speedboat', emoji: '🚤' },
      { type: 'passenger_ship', emoji: '🛳️' },
      { type: 'ferry', emoji: '⛴️' },
      { type: 'motor_boat', emoji: '🛥️' },
      { type: 'ship', emoji: '🚢' },
      { type: 'airplane', emoji: '✈️' },
      { type: 'small_airplane', emoji: '🛩️' },
      { type: 'flight_departure', emoji: '🛫' },
      { type: 'flight_arrival', emoji: '🛬' },
      { type: 'parachute', emoji: '🪂' },
      { type: 'seat', emoji: '💺' },
      { type: 'helicopter', emoji: '🚁' },
      { type: 'suspension_railway', emoji: '🚟' },
      { type: 'mountain_cableway', emoji: '🚠' },
      { type: 'aerial_tramway', emoji: '🚡' },
      { type: 'artificial_satellite', emoji: '🛰️' },
      { type: 'rocket', emoji: '🚀' },
      { type: 'flying_saucer', emoji: '🛸' },
      { type: 'bellhop_bell', emoji: '🛎️' },
      { type: 'luggage', emoji: '🧳' },
      { type: 'hourglass', emoji: '⌛' },
      { type: 'hourglass_flowing_sand', emoji: '⏳' },
      { type: 'watch', emoji: '⌚' },
      { type: 'alarm_clock', emoji: '⏰' },
      { type: 'stopwatch', emoji: '⏱️' },
      { type: 'timer_clock', emoji: '⏲️' },
      { type: 'mantelpiece_clock', emoji: '🕰️' },
      { type: 'clock12', emoji: '🕛' },
      { type: 'clock1230', emoji: '🕧' },
      { type: 'clock1', emoji: '🕐' },
      { type: 'clock130', emoji: '🕜' },
      { type: 'clock2', emoji: '🕑' },
      { type: 'clock230', emoji: '🕝' },
      { type: 'clock3', emoji: '🕒' },
      { type: 'clock330', emoji: '🕞' },
      { type: 'clock4', emoji: '🕓' },
      { type: 'clock430', emoji: '🕟' },
      { type: 'clock5', emoji: '🕔' },
      { type: 'clock530', emoji: '🕠' },
      { type: 'clock6', emoji: '🕕' },
      { type: 'clock630', emoji: '🕡' },
      { type: 'clock7', emoji: '🕖' },
      { type: 'clock730', emoji: '🕢' },
      { type: 'clock8', emoji: '🕗' },
      { type: 'clock830', emoji: '🕣' },
      { type: 'clock9', emoji: '🕘' },
      { type: 'clock930', emoji: '🕤' },
      { type: 'clock10', emoji: '🕙' },
      { type: 'clock1030', emoji: '🕥' },
      { type: 'clock11', emoji: '🕚' },
      { type: 'clock1130', emoji: '🕦' },
      { type: 'new_moon', emoji: '🌑' },
      { type: 'waxing_crescent_moon', emoji: '🌒' },
      { type: 'first_quarter_moon', emoji: '🌓' },
      { type: 'moon', emoji: '🌔' },
      { type: 'full_moon', emoji: '🌕' },
      { type: 'waning_gibbous_moon', emoji: '🌖' },
      { type: 'last_quarter_moon', emoji: '🌗' },
      { type: 'waning_crescent_moon', emoji: '🌘' },
      { type: 'crescent_moon', emoji: '🌙' },
      { type: 'new_moon_with_face', emoji: '🌚' },
      { type: 'first_quarter_moon_with_face', emoji: '🌛' },
      { type: 'last_quarter_moon_with_face', emoji: '🌜' },
      { type: 'thermometer', emoji: '🌡️' },
      { type: 'sunny', emoji: '☀️' },
      { type: 'full_moon_with_face', emoji: '🌝' },
      { type: 'sun_with_face', emoji: '🌞' },
      { type: 'ringed_planet', emoji: '🪐' },
      { type: 'star', emoji: '⭐' },
      { type: 'star2', emoji: '🌟' },
      { type: 'stars', emoji: '🌠' },
      { type: 'milky_way', emoji: '🌌' },
      { type: 'cloud', emoji: '☁️' },
      { type: 'partly_sunny', emoji: '⛅' },
      { type: 'cloud_with_lightning_and_rain', emoji: '⛈️' },
      { type: 'sun_behind_small_cloud', emoji: '🌤️' },
      { type: 'sun_behind_large_cloud', emoji: '🌥️' },
      { type: 'sun_behind_rain_cloud', emoji: '🌦️' },
      { type: 'cloud_with_rain', emoji: '🌧️' },
      { type: 'cloud_with_snow', emoji: '🌨️' },
      { type: 'cloud_with_lightning', emoji: '🌩️' },
      { type: 'tornado', emoji: '🌪️' },
      { type: 'fog', emoji: '🌫️' },
      { type: 'wind_face', emoji: '🌬️' },
      { type: 'cyclone', emoji: '🌀' },
      { type: 'rainbow', emoji: '🌈' },
      { type: 'closed_umbrella', emoji: '🌂' },
      { type: 'open_umbrella', emoji: '☂️' },
      { type: 'umbrella', emoji: '☔' },
      { type: 'parasol_on_ground', emoji: '⛱️' },
      { type: 'zap', emoji: '⚡' },
      { type: 'snowflake', emoji: '❄️' },
      { type: 'snowman_with_snow', emoji: '☃️' },
      { type: 'snowman', emoji: '⛄' },
      { type: 'comet', emoji: '☄️' },
      { type: 'fire', emoji: '🔥' },
      { type: 'droplet', emoji: '💧' },
      { type: 'ocean', emoji: '🌊' },
    ]
  }
];

// Flatten all reactions for quick access
const ALL_REACTIONS = REACTION_CATEGORIES.flatMap(category => category.reactions);

const ExtendedReactions = ({ 
  postId, 
  currentReaction, 
  reactionCounts = {}, 
  onReact, 
  className 
}: ExtendedReactionsProps) => {
  const [isOpen, setIsOpen] = useState(false);
  const [activeCategory, setActiveCategory] = useState(0);

  // Get the most popular reactions to show by default
  const topReactions = ALL_REACTIONS
    .filter(reaction => (reactionCounts[reaction.type] || 0) > 0)
    .sort((a, b) => (reactionCounts[b.type] || 0) - (reactionCounts[a.type] || 0))
    .slice(0, 3);

  // If user has reacted, make sure their reaction is included
  if (currentReaction && !topReactions.find(r => r.type === currentReaction)) {
    const userReaction = ALL_REACTIONS.find(r => r.type === currentReaction);
    if (userReaction) {
      topReactions.unshift(userReaction);
      if (topReactions.length > 3) {
        topReactions.pop();
      }
    }
  }

  const handleReaction = (reactionType: string) => {
    onReact(postId, reactionType);
    setIsOpen(false);
  };

  const getTotalReactions = () => {
    return Object.values(reactionCounts).reduce((sum, count) => sum + count, 0);
  };

  const totalReactions = getTotalReactions();

  return (
    <div className={`flex items-center space-x-2 ${className}`}>
      {/* Quick reaction buttons for top reactions */}
      {topReactions.map((reaction) => {
        const count = reactionCounts[reaction.type] || 0;
        const isSelected = currentReaction === reaction.type;
        
        return (
          <Button
            key={reaction.type}
            variant="ghost"
            size="sm"
            onClick={() => handleReaction(reaction.type)}
            className={`h-8 px-2 text-sm transition-all duration-200 ${
              isSelected 
                ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 scale-105' 
                : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 hover:bg-gray-100 dark:hover:bg-gray-800'
            }`}
          >
            <span className="text-lg mr-1">{reaction.emoji}</span>
            {count > 0 && <span className="text-xs font-medium">{count}</span>}
          </Button>
        );
      })}

      {/* Reaction picker popover */}
      <Popover open={isOpen} onOpenChange={setIsOpen}>
        <PopoverTrigger asChild>
          <Button
            variant="ghost"
            size="sm"
            className="h-8 px-2 text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200"
          >
            <span className="text-lg">😊</span>
            <span className="text-xs ml-1">+</span>
          </Button>
        </PopoverTrigger>
        
        <PopoverContent className="w-80 p-3 max-h-80 overflow-hidden" align="end" side="top" avoidCollisions={true} collisionPadding={10}>
          <div className="space-y-3">
            <h4 className="font-medium text-xs text-gray-900 dark:text-white">
              Choose your reaction
            </h4>
            
            {/* Category Tabs */}
            <div className="flex space-x-1 border-b border-gray-200 dark:border-gray-700">
              {REACTION_CATEGORIES.map((category, index) => (
                <button
                  key={category.name}
                  onClick={() => setActiveCategory(index)}
                  className={`px-2 py-1 text-xs font-medium rounded-t-lg transition-colors ${
                    activeCategory === index
                      ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-700 dark:text-blue-300 border-b-2 border-blue-500'
                      : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200'
                  }`}
                >
                  <span className="mr-1">{category.icon}</span>
                  <span className="hidden sm:inline text-xs">{category.name}</span>
                </button>
              ))}
            </div>

            {/* Reactions Grid */}
            <div className="grid grid-cols-8 gap-1 max-h-40 overflow-y-auto px-1">
              {REACTION_CATEGORIES[activeCategory].reactions.map((reaction) => {
                const count = reactionCounts[reaction.type] || 0;
                const isSelected = currentReaction === reaction.type;
                
                return (
                  <Button
                    key={reaction.type}
                    variant="ghost"
                    onClick={() => handleReaction(reaction.type)}
                    className={`h-8 w-8 p-0 flex items-center justify-center relative transition-all duration-200 flex-shrink-0 ${
                      isSelected 
                        ? 'bg-blue-100 dark:bg-blue-900/30 ring-2 ring-blue-500 scale-105' 
                        : 'hover:bg-gray-100 dark:hover:bg-gray-800'
                    }`}
                  >
                    <span className="text-lg leading-none flex items-center justify-center h-full w-full">{reaction.emoji}</span>
                    {count > 0 && (
                      <Badge 
                        variant="secondary" 
                        className="absolute -top-0.5 -right-0.5 h-3 w-3 rounded-full p-0 flex items-center justify-center text-xs bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200"
                      >
                        {count > 9 ? '9+' : count}
                      </Badge>
                    )}
                  </Button>
                );
              })}
            </div>

            {totalReactions > 0 && (
              <div className="pt-1 border-t border-gray-200 dark:border-gray-700">
                <p className="text-xs text-gray-500 dark:text-gray-400 text-center">
                  {totalReactions} total reaction{totalReactions === 1 ? '' : 's'}
                </p>
              </div>
            )}
          </div>
        </PopoverContent>
      </Popover>

      {/* Total reactions summary (only show if there are reactions and no individual counts shown) */}
      {totalReactions > 0 && topReactions.length === 0 && (
        <Button
          variant="ghost"
          size="sm"
          onClick={() => setIsOpen(true)}
          className="h-8 px-2 text-xs text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200"
        >
          {totalReactions} reaction{totalReactions === 1 ? '' : 's'}
        </Button>
      )}
    </div>
  );
};

export default ExtendedReactions;